name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Dokku server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan s14.michaeloxo.tech >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

      - name: Add Dokku remote and push
        id: dokku_deploy
        run: |
          git remote add dokku dokku@s14.michaeloxo.tech:devops-wordpress
          git push --force dokku main 

      - name: Send Slack notification on success
        if: success() && steps.dokku_deploy.outcome == 'success' 
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "✅ App successfully deployed to devops.s14.michaeloxo.tech!",
              "attachments": [
                {
                  "color": "#36a64f", # Green color
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Repo: <${{ github.repositoryUrl }}|${{ github.repository }}>\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}`\n<${{ github.event.compare }}|View changes>"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      - name: Send Slack notification on failure
        if: failure() 
        uses: slackapi/slack-github-action@v1.26.0 
        with:
          payload: |
            {
              "text": "❌ App deployment to devops.s14.michaeloxo.tech failed!",
              "attachments": [
                {
                  "color": "#ff0000", # Red color
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Repo: <${{ github.repositoryUrl }}|${{ github.repository }}>\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}`\nWorkflow Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run details>"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
