name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Dokku server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan s14.michaeloxo.tech >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

      - name: Add Dokku remote and push
        id: dokku_deploy
        run: |
          git remote add dokku dokku@s14.michaeloxo.tech:devops-wordpress
          git push --force dokku main 

      - name: Send Slack notification on success
        if: success() && steps.dokku_deploy.outcome == 'success' 
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "✅ Deployment Successful\nProject: `${{ github.repository }}`\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}` (<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Commit>)\nTriggered by: `${{ github.actor }}`\nWorkflow Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      - name: Send Slack notification on failure
        if: failure() 
        uses: slackapi/slack-github-action@v1.26.0 
        with:
          payload: |
            {
              "text": "❌ Deployment Failed (Automated Rollback Triggered)\nProject: `${{ github.repository }}`\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}` (<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Commit>)\nTriggered by: `${{ github.actor }}`\nWorkflow Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>\nError: See workflow run logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
